### ISSUE TITLE
denolint: no way to use a config file and check only some folders

### ISSUE THREAD

**Issue by Conaclos** [napi-rs/node-rs#635] opened 2022-05-20 17:36 UTC
Hi!

I would like to include some linting rules and exclude the dist directory.
The `files` field seems not supported in the config file. The combination of a config file and a path as argument seem not supported either (the path is ignored).

I tried the following config file:

```json
{
  "files": {
    "include": ["src/"],
    "exclude": ["dist/"]
  },
  "rules": {
    "tags": ["recommended"],
    "include": [
      "camelcase"
    ]
  }
}
```

And the following commands:

    npx denolint --config denolint.json
    npx denolint --config denolint.json src/

It could be nice whether one of this (or both) could be supported.

**Comment by prantlf** [comment] 2022-09-24 07:59
This seems to be a duplicate of #631.

**Closed** 2024-10-26 15:24 UTC
